name: Super-Linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v8.1.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSX: true
          VALIDATE_TSX: true
          VALIDATE_CSS: true
          VALIDATE_JSON: true
          VALIDATE_YAML: true
          VALIDATE_MARKDOWN: true
          VALIDATE_HTML: true


          FILTER_REGEX_EXCLUDE: |
            .*/(node_modules|\.next|out|build|dist|coverage)/.*
            |.*\.(lock|log|tmp|cache)$
            |.*\.d\.ts$
            |next-env\.d\.ts
            |\.env\..*


          VALIDATE_ALL_CODEBASE: true

          
          DISABLE_ERRORS: true